List<Map<String, dynamic>> patientData = [
  {
    'Name': 'John Doe',
    'Age/Gender': '35 / Male',
    'Status': "Final",
    'Uploaded Date': '2023-10-30',
    'Screened By': 'Dr. Smith',
  },
  {
    'Name': 'Jane Smith',
    'Age/Gender': '28 / Female',
    'Status': "Diagnosis",
    'Uploaded Date': '2023-10-29',
    'Screened By': 'Dr. Johnson',
  },
  {
    'Name': 'Bob Johnson',
    'Age/Gender': '42 / Male',
    'Status': "Final",
    'Uploaded Date': '2023-10-28',
    'Screened By': 'Dr. White',
  },
  {
    'Name': 'Emily Davis',
    'Age/Gender': '31 / Female',
    'Status': "Final",
    'Uploaded Date': '2023-10-27',
    'Screened By': 'Dr. Brown',
  },
  {
    'Name': 'Mark Wilson',
    'Age/Gender': '50 / Male',
    'Status': "Medical",
    'Uploaded Date': '2023-10-26',
    'Screened By': 'Dr. Harris',
  },
  {
    'Name': 'Sophia Clark',
    'Age/Gender': '24 / Female',
    'Status': "Medical",
    'Uploaded Date': '2023-10-25',
    'Screened By': 'Dr. Davis',
  },
  {
    'Name': 'David Lee',
    'Age/Gender': '37 / Male',
    'Status': "Diagnosis",
    'Uploaded Date': '2023-10-24',
    'Screened By': 'Dr. Anderson',
  },
  {
    'Name': 'Olivia Turner',
    'Age/Gender': '29 / Female',
    'Status': "Medical",
    'Uploaded Date': '2023-10-23',
    'Screened By': 'Dr. Martinez',
  },
  {
    'Name': 'William Garcia',
    'Age/Gender': '45 / Male',
    'Status': 'Active',
    'Uploaded Date': '2023-10-22',
    'Screened By': 'Dr. Perez',
  },
  {
    'Name': 'Lily Adams',
    'Age/Gender': '26 / Female',
    'Status': 'Active',
    'Uploaded Date': '2023-10-21',
    'Screened By': 'Dr. Turner',
  },
];
